<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<Project>uSync.Complete.Hangfire</Project>
		<PackageId>uSync.Complete.Hangfire</PackageId>

		<Authors>Kevin Jump</Authors>
		<Company>Jumoo</Company>

		<PackageTags>umbraco usync hangfire umbraco-marketplace</PackageTags>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageIcon>usync-complete.png</PackageIcon>


		<Description>Hangfire helpers for uSync.Complete</Description>
		<Copyright>Copyright © 2024-5 Jumoo</Copyright>

		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/Jumoo/uSync.Hangfire</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Jumoo/uSync.Hangfire</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Infrastructure" Version="17.*" />
		<PackageReference Include="Umbraco.Cms.Infrastructure" Version="17.*" />
		<PackageReference Include="Cultiv.Hangfire" Version="5.2.0">
			<ExcludeAssets>build;buildMultitargeting;buildTransitive</ExcludeAssets>
		</PackageReference>

		<PackageReference Include="uSync.Expansions.Core" Version="17.*" />
		<PackageReference Include="uSync.Publisher" Version="17.*" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../assets/usync-complete.png" Pack="true" PackagePath="\" Visible="false" />
		<None Include="readme.md" Pack="true" PackagePath="\" />
		<None Include="../assets/readme.txt" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
